PokeTypes/Models/Pokemon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PokeTypes.Models {
    public class Pokemon {
        [Key]
        public int Id { get; set; }
        public string PokemonName { get; set; }
        public string Type1 { get; set; }
        public string Type2 { get; set; }

        public string[] types = { "normal", "fighting", "flying", "poison", "ground",
                                         "rock", "bug", "ghost", "steel", "fire", "water",
                                         "grass", "electric", "psychic", "ice", "dragon",
                                         "dark", "fairy" };

        public string[] typeEffectivenessStr(string str1, string str2) {
            double[] te = typeEffectiveness(str1, str2);
            string[] ans = new string[te.Length];
            for(int i=0; i<te.Length; i++) {
                ans[i] = types[i] + ": "+ te[i].ToString();
                ans[i] = ans[i].First().ToString().ToUpper() + ans[i].Substring(1);
            }

            return ans;
        }
        public double[] typeEffectiveness(string str1, string str2) {
            double[,] s = {{1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
                          { 1, 1, 2, 1, 1, .5, .5, 1, 1, 1, 1, 1, 1, 2, 1, 1, .5, 2 },
                          { 1, .5, 1, 1, 0, 2, .5, 1, 1, 1, 1, .5, 2, 1, 2, 1, 1, 1 },
                          { 1, .5, 1, .5, 2, 1, .5, 1, 1, 1, 1, .5, 1, 2, 1, 1, 1, .5 },
                          { 1, 1, 1, .5, 1, .5, 1, 1, 1, 1, 2, 2, 0, 1, 2, 1, 1, 1 },
                          { .5, 2, .5, .5, 2, 1, 1, 1, 2, .5, 2, 2, 1, 1, 1, 1, 1, 1 },
                          { 1, .5, 2, 1, .5, 2, 1, 1, 1, 2, 1, .5, 1, 1, 1, 1, 1, 1 },
                          { 0, 0, 1, .5, 1, 1, .5, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1 },
                          { .5, 2, .5, 0, 2, .5, .5, 1, .5, 2, 1, .5, 1, .5, .5, .5, 1, .5 },
                          { 1, 1, 1, 1, 2, 2, .5, 1, .5, .5, 2, .5, 1, 1, .5, 1, 1, .5 },
                          { 1, 1, 1, 1, 1, 1, 1, 1, .5, .5, .5, 2, 2, 1, .5, 1, 1, 1 },
                          { 1, 1, 2, 2, .5, 1, 2, 1, 1, 2, .5, .5, .5, 1, 2, 1, 1, 1 },
                          { 1, 1, .5, 1, 2, 1, 1, 1, .5, 1, 1, 1, .5, 1, 1, 1, 1, 1 },
                          { 1, .5, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, .5, 1, 1, 2, 1 },
                          { 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, .5, 1, 1, 1 },
                          { 1, 1, 1, 1, 1, 1, 1, 1, 1, .5, .5, .5, .5, 1, 2, 2, 1, 2 },
                          { 1, 2, 1, 1, 1, 1, 2, .5, 1, 1, 1, 1, 1, 0, 1, 1, .5, 2 },
                          { 1, .5, 1, 2, 1, 1, .5, 1, 2, 1, 1, 1, 1, 1, 1, 0, .5, 1 } };

            int indexA = 0;
            int indexB = 0;


            double[] f = new double[18];

            

            for (int i = 0; i < types.Length; i++)
            {
                if (str1 == types[i])
                {
                    indexA = i;
                }
                if (str2 == types[i])
                {
                    indexB = i;
                }
            }


            for (int i = 0; i < 18; i++)
            {
                if (str2 == "") {
                    f[i] = s[indexA, i];
                } else {
                    f[i] = s[indexA, i] * s[indexB, i];
                }
            }

            

            return f;

        }




    }
}

PokeTypes/Controllers/PokemonController.cs
using PokeTypes.Context;
using PokeTypes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PokeTypes.Controllers
{
    public class PokemonController : Controller {
        private PokemonContext db = new PokemonContext();
        // GET: Pokemon
       public ActionResult Index(string searching)
        {
            var pokemons = from s in db.Pokemons select s;
            if (!String.IsNullOrEmpty(searching)) {
                pokemons = pokemons.Where(s => s.PokemonName.ToLower().Contains(searching.ToLower()));
            }
            return View(pokemons.ToList());
        }


        // GET: Pokemon/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pokemon pokemon = db.Pokemons.Find(id);
            if (pokemon == null) {
                return HttpNotFound();
            }
            return View(pokemon);
        }

        // GET: Pokemon/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pokemon/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pokemon/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pokemon/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pokemon/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pokemon/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PokeTypes/Views/Pokemon/Details.cshtml
@model PokeTypes.Models.Pokemon

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Pokemon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PokemonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PokemonName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type1)
        </dd>
        @if (Model.Type2 != "") {
            <dt>
                @Html.DisplayNameFor(model => model.Type2)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type2)
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

<h3>Type effectiveness:</h3><br />

@{ 
    double[] resistances = Model.typeEffectiveness(Model.Type1.ToLower(), Model.Type2.ToLower());
    string[] resStr = Model.typeEffectivenessStr(Model.Type1.ToLower(), Model.Type2.ToLower());
}

<h4>Resistant to:</h4>
<ul>
    @for (int i = 0; i < resistances.Length; i++) {
        if (resistances[i] > 1) {
            <li>
                @resStr[i]
            </li>
        }
    }
</ul>

<h4>Weak to:</h4>
<ul>
@for(int i=0; i<resistances.Length; i++) {
    if(resistances[i] < 1) {
        <li>
            @resStr[i]
        </li>
    }
}
</ul>

PokeTypes/Views/Pokemon/Index.cshtml
@model IEnumerable<PokeTypes.Models.Pokemon>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pokemon:</h2>
@using (Html.BeginForm("Index", "Pokemon", FormMethod.Get)) {
    @Html.TextBox("searching")<input type="submit" value="Search" />
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PokemonName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type2)
        </th>
        <th></th>
    </tr>


@foreach(var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PokemonName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type2)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>